name: Encode

on:
  workflow_dispatch:

jobs:
  publish:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: set# Checksum for provenance must be calculated before moving artifacts temporarily
        id: set
        run: |
          MULTI_LINES_TEXT="this is line one \n
                  this is line two \n
                  this is line three \n"

          electron_binary_artifacts="test \n
                                     test 1 \n
                                     test2 \n"
                                    

          echo "electron_binary_artifacts_var<<EOF" >> $GITHUB_ENV
          # here we can place the command that will generate multi-line text
          echo $electron_binary_artifacts >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: do
        run: |
          echo "${{ env.electron_binary_artifacts_var }}"
          electron_binary_artifact_digest_base64=$(echo "${electron_binary_artifacts_var}" | base64 -w0)
          echo "Electron Binary Artifact digest:"
          echo "${electron_binary_artifact_digest_base64}"

          echo "Decoding the base64 digest"
          echo "${electron_binary_artifact_digest_base64}" | base64 -d
    
